export const slides = [
  {
    title: "intro",
    src: "/Slides/intro.png",
    position: [0, 0, -100],
    trigger: ".a",
    direction: "center",
  },
  {
    title: "Slide1",
    src: "/Slides/s1.png",
    position: [0, -100, -200],
    trigger: ".b",
    direction: "up",
  },
  {
    title: "Slide2",
    src: "/Slides/s2.png",
    position: [0, 0, -300],
    trigger: ".c",
    direction: "down",
  },
  {
    title: "Slide3",
    src: "/Slides/s3.png",
    position: [0, 0, -400],
    trigger: ".d",
    direction: "center",
  },
  {
    title: "Slide4",
    src: "/Slides/s4.png",
    position: [0, 0, -500],
    trigger: ".e",
    direction: "center",
  },
  {
    title: "Slide5",
    src: "/Slides/s5.png",
    position: [0, 0, -600],
    trigger: ".f",
    direction: "center",
  },
  {
    title: "Slide6",
    src: "/Slides/s6.png",
    position: [0, 0, -700],
    trigger: ".g",
    direction: "center",
  },
  {
    title: "Slide7",
    src: "/Slides/s7.png",
    position: [0, 0, -800],
    trigger: ".h",
    direction: "center",
  },
  {
    title: "Slide8",
    src: "/Slides/s8.png",
    position: [0, 0, -900],
    trigger: ".i",
    direction: "center",
  },
];
