export const slides = [
  {
    title: "intro",
    src: "/Slides/intro.png",
    position: [0, 0, -100],
    trigger: ".a",
    direction: "center",
  },
  {
    title: "lucyVideo",
    src: "/Slides/Video/lucy.mp4",
    position: [0, 0, -200],
    trigger: ".b",
    direction: "center",
    isVideo: true,
  },
  {
    title: "Slide1",
    src: "/Slides/s1.jpg",
    position: [500, 0, -300],
    trigger: ".c",
    direction: "right",
  },
  {
    title: "Slide2",
    src: "/Slides/s2.jpg",
    position: [-500, 0, -400],
    trigger: ".d",
    direction: "left",
  },
  {
    title: "Slide3",
    src: "/Slides/s3.jpg",
    position: [0, 100, window.innerWidth < 500 ? -5 : 2],
    trigger: ".e",
    direction: "down",
  },
  {
    title: "Slide4",
    src: "/Slides/s4.jpg",
    position: [0, -100, window.innerWidth < 500 ? -5 : 2],
    trigger: ".f",
    direction: "up",
  },
  {
    title: "Slide5",
    src: "/Slides/s5.jpg",
    position: [0, 0, -700],
    trigger: ".g",
    direction: "center",
  },
  {
    title: "Slide6",
    src: "/Slides/s6.jpg",
    position: [0, 0, -800],
    trigger: ".h",
    direction: "center",
  },
  {
    title: "Slide7",
    src: "/Slides/s7.jpg",
    position: [0, 0, -900],
    trigger: ".i",
    direction: "center",
  },
  {
    title: "Slide8",
    src: "/Slides/s8.jpg",
    position: [0, 0, -1000],
    trigger: ".j",
    direction: "center",
  },
  {
    title: "Slide9",
    src: "/Slides/s9.jpg",
    position: [0, 0, -1100],
    trigger: ".k",
    direction: "center",

  },
  {
    title: "Slide10",
    src: "/Slides/s10.jpg",
    position: [0, 0, -1200],
    trigger: ".l",
    direction: "center",
  },
  {
    title: "Slide11",
    src: "/Slides/s11.jpg",
    position: [0, 0, -1300],
    trigger: ".m",
    direction: "center"
  },
];
